version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  graphql-server:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydatabase

